apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
status:
  loadBalancer:
    ingress:
    - ip: 192.1.2.2