# deplyoment for nginx-image
# create 3 pods
# kubectl get name-service {deploy/deplyoment|service/svc|pods}
# kubectl create -f file.yml
# kubectl delete name-service deploy deploy-name

apiVersion: apps/v1

kind: Deployment  # {pod,service,replicaset,ASG}


metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 2shad/shadman_nginx
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
  type: NodePort