apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.96.0.1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1